require: rubocop-rails
AllCops:
  Exclude:
  - node_modules/**/*
  - db/**/*
  - bin/**/*
  - Guardfile
  DisplayCopNames: true
  DisplayStyleGuide: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.7

Gemspec/DateAssignment:
  Enabled: true
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/DotPosition:
  EnforcedStyle: leading
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/LeadingCommentSpace:
  Enabled: true
Layout/LineLength:
  Enabled: true
  Max: 100
  AllowURI: true
  IgnoreCopDirectives: true
  Exclude:
  - config/routes.rb
Layout/SpaceAfterColon:
  Enabled: true
Layout/SpaceAfterComma:
  Enabled: true
Layout/SpaceAfterMethodName:
  Enabled: true
Layout/SpaceAfterNot:
  Enabled: true
Layout/SpaceAfterSemicolon:
  Enabled: true
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true
  EnforcedStyle: space
Layout/SpaceAroundKeyword:
  Enabled: true
Layout/SpaceAroundOperators:
  Enabled: true
Layout/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: space
Layout/SpaceBeforeBrackets:
  Enabled: true
Layout/SpaceBeforeComma:
  Enabled: true
Layout/SpaceBeforeComment:
  Enabled: true
Layout/SpaceBeforeFirstArg:
  Enabled: true
Layout/SpaceBeforeSemicolon:
  Enabled: true
Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: true
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
Layout/SpaceInsideParens:
  Enabled: true
Layout/SpaceInsideRangeLiteral:
  Enabled: true
Layout/TrailingEmptyLines:
  Enabled: true
  EnforcedStyle: final_newline
Layout/TrailingWhitespace:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true
Lint/AssignmentInCondition:
  Enabled: true
  AllowSafeAssignment: true
Lint/Debugger:
  Enabled: true
Lint/DeprecatedClassMethods:
  Enabled: true
Lint/DeprecatedConstants:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/EmptyClass:
  Enabled: true
Lint/FlipFlop:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
Lint/LiteralInInterpolation:
  Enabled: true
Lint/Loop:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/NumberedParameterAssignment:
  Enabled: true
Lint/OrAssignmentToConstant:
  Enabled: true
Lint/ParenthesesAsGroupedExpression:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Lint/RequireParentheses:
  Enabled: false
Lint/SuppressedException:
  Enabled: true
Lint/SymbolConversion:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Lint/UnderscorePrefixedVariableName:
  Enabled: true
Lint/UnexpectedBlockArity:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Lint/UselessSetterCall:
  Enabled: true

Metrics/AbcSize:
  Enabled: true
  Max: 25
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: true
  Max: 5
Metrics/ClassLength:
  Enabled: true
  CountComments: false
  Max: 500
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 10
Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 100
Metrics/ModuleLength:
  Enabled: true
  CountComments: false
  Max: 500
Metrics/ParameterLists:
  Enabled: true
  Max: 5
  CountKeywordArgs: false
Metrics/PerceivedComplexity:
  Enabled: true
  Max: 8

Naming/AccessorMethodName:
  Enabled: true
Naming/AsciiIdentifiers:
  Enabled: true
Naming/FileName:
  Enabled: true
  Exclude:
  - "**/jsonapi-resources.rb"
Naming/PredicateName:
  Enabled: true
  NamePrefix:
  - is_
  - has_
  - have_
  ForbiddenPrefixes:
  - is_
Naming/VariableName:
  Enabled: true
  EnforcedStyle: snake_case

Rails/ActiveRecordCallbacksOrder:
  Enabled: true
Rails/AfterCommitOverride:
  Enabled: true
Rails/AttributeDefaultBlockValue:
  Enabled: true
Rails/FindById:
  Enabled: true
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/Inquiry:
  Enabled: true
Rails/MailerName:
  Enabled: true
Rails/MatchRoute:
  Enabled: true
Rails/NegateInclude:
  Enabled: true
Rails/Pluck:
  Enabled: true
Rails/PluckInWhere:
  Enabled: true
Rails/RenderInline:
  Enabled: true
Rails/RenderPlainText:
  Enabled: true
Rails/ShortI18n:
  Enabled: true
Rails/SquishedSQLHeredocs:
  Enabled: true
Rails/TimeZone:
  Enabled: false
Rails/WhereEquals:
  Enabled: true
Rails/WhereExists:
  Enabled: true
Rails/WhereNot:
  Enabled: true

Security/Eval:
  Enabled: true

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method
Style/ArgumentsForwarding:
  Enabled: true
Style/ArrayJoin:
  Enabled: true
Style/AsciiComments:
  Enabled: false
Style/Attr:
  Enabled: true
Style/BlockComments:
  Enabled: true
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
  - app/graphql/**/*
Style/CollectionCompact:
  Enabled: true
Style/CollectionMethods:
  PreferredMethods:
    collect: map
    collect!: map!
    inject: reduce
    detect: find
    find_all: select
Style/ColonMethodCall:
  Enabled: true
Style/CommentAnnotation:
  Enabled: true
  Keywords:
  - TODO
  - FIXME
  - OPTIMIZE
  - HACK
  - REVIEW
  - DEPRECATED
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/EmptyLiteral:
  Enabled: true
Style/EndlessMethod:
  Enabled: true
Style/EvenOdd:
  Enabled: true
Style/FormatString:
  Enabled: true
  EnforcedStyle: format
Style/FrozenStringLiteralComment:
  Enabled: true
  AutoCorrect: true
Style/GlobalVars:
  Enabled: false
Style/GuardClause:
  Enabled: true
  MinBodyLength: 3
Style/HashConversion:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashExcept:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/IfUnlessModifier:
  Enabled: true
Style/IfWithBooleanLiteralBranches:
  Enabled: true
Style/IfWithSemicolon:
  Enabled: true
Style/InlineComment:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
  Enabled: true
Style/LambdaCall:
  Enabled: true
Style/MethodCalledOnDoEndBlock:
  Enabled: true
Style/MultilineBlockChain:
  Enabled: true
Style/MultilineTernaryOperator:
  Enabled: true
Style/NegatedIf:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NestedTernaryOperator:
  Enabled: true
Style/Next:
  Enabled: true
  MinBodyLength: 3
Style/NilComparison:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/Not:
  Enabled: true
Style/NumericLiterals:
  Enabled: true
  MinDigits: 5
Style/OneLineConditional:
  Enabled: true
Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    "%": "[]"
    "%i": "[]"
    "%q": "[]"
    "%Q": "[]"
    "%r": "{}"
    "%s": "()"
    "%w": "[]"
    "%W": "[]"
    "%x": "[]"
Style/PerlBackrefs:
  Enabled: true
Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: exploded
Style/RedundantArgument:
  Enabled: true
Style/RedundantBegin:
  Enabled: true
Style/RedundantSelf:
  Enabled: true
Style/RescueModifier:
  Enabled: true
Style/SelfAssignment:
  Enabled: true
Style/SingleLineMethods:
  Enabled: true
  AllowIfMethodIsEmpty: true
Style/SpecialGlobalVars:
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/SwapValues:
  Enabled: true
Style/SymbolArray:
  Enabled: true
Style/SymbolProc:
  Enabled: true
Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: no_comma
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: no_comma
Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: no_comma
Style/TrivialAccessors:
  Enabled: true
  AllowDSLWriters: true
Style/UnlessElse:
  Enabled: true
Style/VariableInterpolation:
  Enabled: true
Style/WhenThen:
  Enabled: true
Style/WordArray:
  Enabled: true
  MinSize: 2
