default: &default
  adapter: postgresql
  encoding: unicode
  prepared_statements: false
  advisory_locks: false
<% if ENV.include?('DATABASE_URL') %>
  url: <%= ENV.fetch('DATABASE_URL') %>
<% end %>
<% if $0.include?('rake') %>
  connect_timeout: 5
  connect_timeout: 5
  variables:
    lock_timeout: 10s
<% else %>
  pool: <%= (ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 40) %>
  connect_timeout: 5
  checkout_timeout: 2
  reaping_frequency: 30
  variables:
    lock_timeout: 6s
    statement_timeout: 15s
<% end %>

development:
  <<: *default
  database: genkan_development

test:
  <<: *default
  database: genkan_test

production:
  <<: *default
  database: genkan_production
